name: Build container

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      ContainerRegistry: ghcr.io
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
         global-json-file: global.json
         cache: true
         cache-dependency-path: src/ActionsTestResultAction/packages.lock.json

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.ContainerRegistry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        env:
          ContainerImageTags: ${{ github.sha }};${{ github.ref_name }}
        run: dotnet publish -t:PublishContainer -r linux-musl-x64 -bl

      - name: Upload binlogs
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: binlogs-${{ runner.os }}
          path: '*.binlog'
          retention-days: 7
